//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalleMaint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSpiller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSpiller()
        {
            this.tblSpils = new HashSet<tblSpil>();
        }
    
        public int spillerPK { get; set; }
        public string spillerForNavn { get; set; }
        public string spillerEfterNavn { get; set; }
        public Nullable<System.DateTime> spillerOptagelsesDato { get; set; }
        public Nullable<short> spillerFunktion { get; set; }
        public Nullable<System.DateTime> spillerUdmeldt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSpil> tblSpils { get; set; }
    }
}
